### ISSUE TITLE
Shouldn't gdk-event-button-state be a gdk-modifier-type instead of a :uint? 

### ISSUE THREAD

**Issue by Ambrevar** [Ferada/cl-cffi-gtk#39]
See https://github.com/crategus/cl-cffi-gtk/issues/74

Fixed here:
https://github.com/crategus/cl-cffi-gtk/commit/020c5febdc04962de378f328ec3a4de9c81fdd80

Test here: https://github.com/crategus/cl-cffi-gtk/commit/2e240eb260560000cabc7ee2431a036650f02a2b

**Comment by Ferada** [comment]
Fixed by 412d17214e092220c65a5660f5cbbd9cb69b8fe4.
